version: "3"

services:
  nginx:
    container_name: nginx
    build:
      context: .
    restart: always
    ports:
        - "80:80"
        - "443:443"
    volumes:
        #- /etc/letsencrypt:/etc/nginx/ssl
      - /etc/letsencrypt:/etc/letsencrypt
        #- /var/www/certbot:/var/www/certbot
      - /home/data/www/certbot:/var/www/certbot
    environment:
        # Create htpasswd user
        - USERNAME=Hello
        - USERPWD=Hello
        - USERNAME2=Hello
        - USERPWD2=Hello
        - SubDomain=localhost
        - PrimaryDomain=localhost
        - Jdownloader2=true
        - Netdata=true
        - Photoprism=true
        - Transimission=true
        - Codeserver=true
        - Jellyfin=true
        - Jellyfin2=true
        - Jenkins=true
        - Nextcloud=true
        - Tomcat=true