name: deployment

on:
  push:
    branches: master

dockerImageBuild:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest
          build-args: |
            arg1=value1
            arg2=value2
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

Deploy:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    
    steps:    
    - uses: actions/checkout@v2
    - name: executing remote ssh commands using password
      if: github.event_name == 'pull_request'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.Deploy_Server_HOST }}
        username: ${{ secrets.Deploy_Server_USERNAME }}
        password: ${{ secrets.Deploy_Server_PASSWORD }}
        port: ${{ secrets.PORT }} # default : 22
        passphrase: ${{ secrets.Deploy_Ssh_PASSPHRASE }}
        script: |
          cd ${{ secrets.Deploy_Server_PATH }} && git pull
          sh dc.sh